name: export-and-branch-solution
#  Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes
on:
  workflow_dispatch:
  
env:
  PP_ENV_URL: https://org6d1b2125.crm.dynamics.com
  PP_CLIENT_ID: 839f4ef5-623e-434d-add1-25849fd54c02
  PP_TENANT_ID: fba980db-2369-4792-bceb-8b5212a2223a
  PP_SOLUTION_NAME: TMobile
  PP_SOLUTION_OUTPUT_FILE: out/exported/TMobile.zip
  PP_SOLUTION_FOLDER: out/solutions/TMobile
  PP_SOLUTION_TARGET_FOLDER: solutions/TMobile
    

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ env.PP_ENV_URL }}
        app-id: ${{ env.PP_CLIENT_ID }}
        client-secret: ${{ secrets.PP_GH_ACTIONS_SECRET }}
        tenant-id: ${{ env.PP_TENANT_ID }}
        

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ env.PP_ENV_URL }}
        app-id: ${{ env.PP_CLIENT_ID }}
        client-secret: ${{ secrets.PP_GH_ACTIONS_SECRET }}
        tenant-id: ${{ env.PP_TENANT_ID }}
        solution-name: ${{ env.PP_SOLUTION_NAME }}
        solution-output-file: ${{ env.PP_SOLUTION_OUTPUT_FILE }}

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ env.PP_SOLUTION_OUTPUT_FILE }}
        solution-folder: ${{ env.PP_SOLUTION_FOLDER }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ env.PP_SOLUTION_FOLDER }}
        solution-target-folder: ${{ env.PP_SOLUTION_TARGET_FOLDER }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
